<head>
    <title>Lista de Tareas</title>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <div class="bg-white p-6 rounded-lg shadow-lg">
            <h2 class="text-2xl font-bold mb-4">To Do</h2>
            <div class="mb-4">
                <button class="bg-green-500 text-white px-4 py-2 rounded" onclick="window.location.href='<?php echo WEB_ROOT?>/create'">+ Crear Nueva Tarea</button>
            </div>
            <!--<ul class="divide-y divide-gray-200">-->
                <!-- Ejemplo de tarea -->
                <!--<li class="py-4 flex justify-between items-center">-->
                    <!--<div>
                        <h3 class="text-lg font-bold">Nombre de la tarea</h3>
                        <p>Descripción de la tarea</p>
                    </div>-->
                  <div class="flex space-x-4">
                    <?php
                      if(count($this->tareas) > 0) :
                    ?>
                      <div class="w-1/3">
                        <h2 class="text-lg font-bold">Pendiente</h2>
                        <?php
                          if(count($this->tareasPendiente) > 0) :
                            foreach($this->tareasPendiente as $tarea) :
                        ?>
                            <h3 class='text-lg'> <?= $tarea['titulo'];?> </h3>
                            <p> <?= $tarea['descripcion'];?> </p> 
                            <p> <?= $tarea['estado']; ?> </p>
                            <p> <?= $tarea['hora_inicio']; ?> </p>
                            <p> <?= $tarea['hora_fin']; ?> </p>
                            <p> <?= $tarea['creado_en']; ?> </p>
                            <p> <?= $tarea['usuario']; ?> </p>
                            <div class='flex space-x-2'>
                              <form method="POST" action="update/<?= $tarea['id']?>">
                                <button class='bg-yellow-500 text-white px-4 py-2 rounded' onclick="window.location.href='update/<?$tarea['id']?>'">

                                  Editar
                                </button>
                              </form>
                              <form method="POST" action="delete/<?=$tarea['id']?>">
                                <button class='bg-red-500 text-white px-4 py-2 rounded' onclick='confirmDelete(1)'>Eliminar</button>
                                <input type="hidden" name="id" id="<?=$tarea['id']?>"/>
                              </form>
                            </div>
                            <br>
                            <?php endforeach;?>
                        <?php else : ?>
                          <h3 class='text-lg'>No hay tareas pendientes</h3><br>
                        <?php endif;?>
                      </div>
                      <div class="w-1/3">
                        <h2 class="text-lg font-bold">En progreso</h2>
                        <?php
                          if(count($this->tareasEnProgreso) > 0) :
                            foreach($this->tareasEnProgreso as $tarea) :
                        ?>
                            <h3 class='text-lg'> <?= $tarea['titulo'];?> </h3>
                            <p> <?= $tarea['descripcion'];?> </p> 
                            <p> <?= $tarea['estado']; ?> </p>
                            <p> <?= $tarea['hora_inicio']; ?> </p>
                            <p> <?= $tarea['hora_fin']; ?> </p>
                            <p> <?= $tarea['creado_en']; ?> </p>
                            <p> <?= $tarea['usuario']; ?> </p>
                            <div class='flex space-x-2'>
                              <form method="POST" action="update/<?= $tarea['id']?>">
                                <button class='bg-yellow-500 text-white px-4 py-2 rounded' onclick="window.location.href='update/<?$tarea['id']?>'">

                                  Editar
                                </button>
                              </form>
                              <form method="POST" action="delete/<?=$tarea['id']?>">
                                <button class='bg-red-500 text-white px-4 py-2 rounded' onclick='confirmDelete(1)'>Eliminar</button>
                                <input type="hidden" name="id" id="<?=$tarea['id']?>"/>
                              </form>
                            </div>
                            <br>
                            <?php endforeach;?>
                        <?php else : ?>
                          <h3 class='text-lg'>No hay tareas en progreso</h3><br>
                        <?php endif;?>
                      </div>
                      <div class="w-1/3">
                        <h2 class="text-lg font-bold">Completado</h2>
                        <?php
                          if(count($this->tareasCompletado) > 0) :
                            foreach($this->tareasCompletado as $tarea) :
                        ?>
                            <h3 class='text-lg'> <?= $tarea['titulo'];?> </h3>
                            <p> <?= $tarea['descripcion'];?> </p> 
                            <p> <?= $tarea['estado']; ?> </p>
                            <p> <?= $tarea['hora_inicio']; ?> </p>
                            <p> <?= $tarea['hora_fin']; ?> </p>
                            <p> <?= $tarea['creado_en']; ?> </p>
                            <p> <?= $tarea['usuario']; ?> </p>
                            <div class='flex space-x-2'>
                              <form method="POST" action="update/<?= $tarea['id']?>">
                                <button class='bg-yellow-500 text-white px-4 py-2 rounded' onclick="window.location.href='update/<?$tarea['id']?>'">

                                  Editar
                                </button>
                              </form>
                              <form method="POST" action="delete/<?=$tarea['id']?>">
                                <button class='bg-red-500 text-white px-4 py-2 rounded' onclick='confirmDelete(1)'>Eliminar</button>
                                <input type="hidden" name="id" id="<?=$tarea['id']?>"/>
                              </form>
                            </div>
                            <br>
                            <?php endforeach;?>
                        <?php else : ?>
                          <h3 class='text-lg'>No hay tareas completadas</h3><br>
                        <?php endif;?>
                      </div>
                      
                    <?php endif;?>
                </div>
                    <!--</div>
                </li>
                 Más tareas aquí 
            </ul>-->
        </div>
    </div>

    <script>
        function confirmDelete(id) {
            if (confirm('¿Estás seguro que quieres eliminar esta tarea?')) {
                // Lógica para eliminar la tarea
                alert('Tarea eliminada');
                // Redirigir o recargar la página después de eliminar
            }
        }
    </script>
</body>
</html>